# Generated by Django 2.1.6 on 2019-03-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(max_length=64)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('num_of_vertices', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
